### ISSUE TITLE
"Announce" button does not properly support doubleclick

### ISSUE THREAD

**Issue by joedetode** [TechPhil/TrainAnnouncer#1]
When clicking "announce" multiple times, the text written is looped however meny times you clicked it. Windows 7 ultimate x64.

**Comment by TechPhil** [comment]
Hi there Joe, unfortunately this is a limitation of Windows Forms and C#. The only way you would be able to fix this is by adding in multiple threads, but then you would get a horrible overlap. I am working on a solution where you can 'stack' announcements.
